name: Java CI with Gradle

on:
  pull_request:
    branches: [ llama ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@main
        with:
           cache-read-only: false
           allow-snapshot-wrappers: true
      - name: Set up JDK 8
        uses: actions/setup-java@main
        with:
          java-version: 8
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --stacktrace --info
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@main
        with:
          name: OptiFabric-Artifact
          path: build/libs/optifabric-*.*.jar
          if-no-files-found: error
